const NAMES = [
  "Socrates",
  "Plato",
  "Aristotle",
  "Heraclitus",
  "Diogenes",
  "Hypatia",
  "Augustine",
  "Aquinas",
  "Descartes",
  "Spinoza",
  "Leibniz",
  "Locke",
  "Berkeley",
  "Hume",
  "Voltaire",
  "Rousseau",
  "Kant",
  "Hegel",
  "Schopenhauer",
  "Kierkegaard",
  "Mill",
  "Nietzsche",
  "James",
  "Russell",
  "Wittgenstein",
  "Heidegger",
  "Sartre",
  "Camus",
  "de Beauvoir",
  "Arendt",
  "Popper",
  "Foucault",
  "Derrida",
  "Rawls",
  "Quine",
  "Chomsky",
  "Confucius",
  "Laozi",
  "Mencius",
  "Zhuangzi",
  "Nagarjuna",
  "Avicenna",
  "Averroes",
  "Maimonides",
  "Boethius",
];

export function randomAgentName(exclude: string[] = []): string {
  const available = NAMES.filter((n) => !exclude.includes(n));
  const pool = available.length > 0 ? available : NAMES;
  return pool[Math.floor(Math.random() * pool.length)];
}
